### ISSUE TITLE
How can record  media  in browser platform?

### ISSUE THREAD

**Issue by yanglezyq** [ErikSchierboom/ionic2-audio-recorder#4]
Now, I can record a video in the Android / iOS APP。
But not work in the mobile web browser.

I try excute that command:
~# ionic add platform browser
~#  ionic run browser

but that only can open the camera in the PC Chrome.
In the iPhone or Android device , run in safari 、 chrome or other browser . will report an error:  `cordovar_unsupport_camera`

but at http://ionicframework.com/docs/native/media/ . it write 
Android
BlackBerry 10
**Browser**
iOS
Tizen
Ubuntu
Windows
Windows Phone

so , what should I do ? thx...

**Comment by ErikSchierboom** [comment]
@yanglezyq You should take a look at Ionic Native Mocks: https://github.com/chrisgriffith/ionic-native-mocks
